name: Update Clash, Surge and Stash AD Domain Lists

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 UTC 时间 2 点执行（北京时间 10 点）
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and generate domain lists
        run: |
          mkdir -p AD-domain/Clash AD-domain/Surge AD-domain/Stash

          # 下载 anti-AD 的 Surge 格式源，去除注释和前缀
          curl -sSL https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt -o anti-ad.txt
          grep -vE '^\s*#' anti-ad.txt | sed '/^\s*$/d' | sed 's/^DOMAIN-SUFFIX,//' > clean1.txt

          # 定义多个 Hagezi 源列表
          urls=(
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/popupads-onlydomains.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.mini-onlydomains.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.huawei-onlydomains.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.winoffice-onlydomains.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.samsung-onlydomains.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.tiktok.extended-onlydomains.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.vivo-onlydomains.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.oppo-realme-onlydomains.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.xiaomi-onlydomains.txt"
          )

          # 下载并清洗所有 Hagezi 域名列表
          > clean_hagezi.txt
          for url in "${urls[@]}"; do
            curl -sSL "$url" | grep -vE '^\s*#' | sed '/^\s*$/d' >> clean_hagezi.txt
          done

          # 合并、统一格式、去重，得到纯域名
          cat clean1.txt clean_hagezi.txt \
            | sed 's/^\.//' \
            | sort -u > raw_domains.txt

          # 保存一份纯域名列表到仓库根目录
          cp raw_domains.txt AD-domains.txt

          # 生成 Surge 格式（加上前缀）
          sed 's/^/DOMAIN-SUFFIX,/' raw_domains.txt > AD-domain/Surge/AD-domain.list

          # 生成 Clash 格式 YAML
          {
            echo "payload:"
            sed 's/^/  - DOMAIN-SUFFIX,/' raw_domains.txt
          } > AD-domain/Clash/AD-domain.yaml

          # 生成 Stash 格式（去除多余空格，正确的 +. 格式）
          {
            sed 's/^/+./' raw_domains.txt
          } > AD-domain/Stash/AD-domain.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [[ $(git status --porcelain AD-domain/ AD-domains.txt) ]]; then
            git add AD-domains.txt
            git add AD-domain/Clash/AD-domain.yaml
            git add AD-domain/Surge/AD-domain.list
            git add AD-domain/Stash/AD-domain.txt
            git commit -m "Update AD domain lists on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
