name: Update Clash and Surge AD Domain List

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 UTC 时间 2 点执行（北京时间 10 点）
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and generate Clash and Surge-compatible formats
        run: |
          mkdir -p AD-domain/Clash AD-domain/Surge

          # 下载新源文件（Surge 格式），去掉注释和前缀
          curl -sSL https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt -o anti-ad.txt
          grep -vE '^\s*#' anti-ad.txt | sed '/^\s*$/d' | sed 's/^DOMAIN-SUFFIX,//' > clean1.txt

          # 下载第二个源文件（纯域名格式）
          curl -sSL https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate-onlydomains.txt -o list2.txt
          grep -vE '^\s*#' list2.txt | sed '/^\s*$/d' > clean2.txt

          # 合并、去重、重新添加统一前缀
          cat clean1.txt clean2.txt \
            | sed 's/^\.//' \
            | sed 's/^/DOMAIN-SUFFIX,/' \
            | sort -u > tmp_domains.txt

          # 生成 Clash 格式 YAML 文件
          {
            echo "payload:"
            sed 's/^/  - /' tmp_domains.txt
          } > AD-domain/Clash/AD-domain.yaml

          # 生成 Surge 格式文件
          cp tmp_domains.txt AD-domain/Surge/AD-domain.list

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [[ `git status --porcelain` ]]; then
            git add AD-domain/Clash/AD-domain.yaml
            git add AD-domain/Surge/AD-domain.list
            git commit -m "Update AD domain list for Clash and Surge on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
